<?php
@include("../../inc/header.php");

/*
		SoftName : EmpireBak
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

E_D("DROP TABLE IF EXISTS `phome_ecms_news_data_1`;");
E_C("CREATE TABLE `phome_ecms_news_data_1` (
  `id` int(11) NOT NULL DEFAULT '0',
  `classid` smallint(6) NOT NULL DEFAULT '0',
  `writer` varchar(30) NOT NULL DEFAULT '',
  `befrom` varchar(60) NOT NULL DEFAULT '',
  `newstext` mediumtext NOT NULL,
  PRIMARY KEY (`id`),
  KEY `classid` (`classid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8");
E_D("replace into `phome_ecms_news_data_1` values('96','58','忘记的话','杀跌发生的发生','<p>山东分公司东风公司的范甘迪风格山东分公司东风个&nbsp;</p>');");
E_D("replace into `phome_ecms_news_data_1` values('97','60','','','<p>撒旦发生大幅&nbsp;</p>');");
E_D("replace into `phome_ecms_news_data_1` values('98','60','','','<p>阿斯顿发生的&nbsp;</p>');");
E_D("replace into `phome_ecms_news_data_1` values('99','64','','','<p>阿斯顿发生发&nbsp;</p>');");
E_D("replace into `phome_ecms_news_data_1` values('100','64','','','<p>阿斯顿发生的&nbsp;</p>');");
E_D("replace into `phome_ecms_news_data_1` values('101','65','','','<p>阿斯顿发生的和&nbsp;</p>');");
E_D("replace into `phome_ecms_news_data_1` values('102','60','','','<p>杀跌发生的&nbsp;</p>');");
E_D("replace into `phome_ecms_news_data_1` values('103','66','','','<p>杀跌发生的&nbsp;</p>');");
E_D("replace into `phome_ecms_news_data_1` values('104','66','网易','网易','<p align=\"center\" style=\"text-indent: 2em\"><strong><img border=\"0\" alt=\"\" src=\"http://cimg20.163.com/2008/2008/5/8/20080508102532f1caa.jpg\" /></strong></p>\r\n<p align=\"center\" style=\"text-indent: 2em\">&nbsp;</p>\r\n<p align=\"center\" style=\"text-indent: 2em\"><strong><img border=\"0\" alt=\"\" src=\"http://cimg20.163.com/2008/2008/5/8/20080508093055a04fc.jpg\" /><br />\r\n</strong>队员在珠峰展示五环旗<br />\r\n&nbsp;</p>\r\n<center><center><center><strong><img border=\"0\" alt=\"\" src=\"http://cimg20.163.com/2008/2008/5/8/200805080921490fe71.jpg\" /><br />\r\n</strong>圣火照亮珠峰<br />\r\n</center><strong><img border=\"0\" alt=\"\" src=\"http://cimg21.163.com/2008/2008/5/8/20080508091958e2cc4.jpg\" /><br />\r\n</strong>火炬手在珠峰峰顶传递<br />\r\n</center><strong><center><img border=\"0\" alt=\"\" src=\"http://cimg20.163.com/2008/2008/5/8/200805080933510c24f.jpg\" /><br />\r\n</center></strong>火炬点燃瞬间</center>\r\n<p style=\"text-indent: 2em\"><strong>珠峰登山队成功登顶 奥运圣火点燃在世界之巅</strong></p>');");
E_D("replace into `phome_ecms_news_data_1` values('105','66','腾讯','腾讯','<p align=\"center\"><img src=\"http://img1.qq.com/sports/pics/10300/10300429.jpg\" border=\"0\" /><br /><strong>科比终于正式接过了本赛季MVP奖杯</strong></p><p style=\"TEXT-INDENT: 2em\">成名这么久远了，科比终于被证实“最有价值”。其实，在世人出于公心的天平上，这位可以与神直接通话的妖人，早已在价值评估体系中占据了统治地位。这次，他仅仅是得到了官方的接纳与认可。全美记者把选票打包一般邮寄给了他，这是通过汗水和血水贿选得来的。据说，在很长一段时间里，科比总喜欢和记者把关系搞僵。现在，科比还是那么牛逼，那么自傲，那么目中无人，那么有折腾劲儿。 </p><p style=\"TEXT-INDENT: 2em\">这是一个对荣誉永远保持饥饿感的男人。他不缺冠军戒指，习惯了腻歪透顶的赢球方式。即便如此，他依然不断向球队索取敲诈胜利。赛季之初，他大骂队友斯玛什·帕克为“极品垃圾”，并要求俱乐部立刻让他从眼前消失。于是，帕克被赶紧打发走了。他是天生的特权球员，飞扬跋扈，大权独揽。他拥有联盟惟一的交易否决选项，拥有挑选队友的生杀权限。他曾经怂恿俱乐部总经理利用拜纳姆来兑换基德，遭否后便大骂总经理“混蛋”。于是，他只得把“自己”作为筹码抛投出去，以离队威胁球队做出改变，迅速强大。如此“雷人”的言论当然会使上峰震怒，就像一位员工总是不断挑拨同事关系扰乱军心，即便是出于好心也会使老板感到不快与拧巴。但，这次闹事的是科比，这是一位大爷，这是一尊大佛，这是一个天真顽劣大声哭闹的大男孩。你惟一可以使局势改观的做法就是哄着他，然后告诉他，叔孰给你买糖吃。 </p><p style=\"TEXT-INDENT: 2em\">随后，湖人总经理出手了。一出手便是大手笔，几乎不废一枪一弹就把加索尔拉来给科比作玩伴儿。这下，男孩儿破涕为笑，不吵不闹，就像是将一颗大白兔兔奶糖含在了小嘴巴里，终于可以蹦蹦跳跳地自个儿玩去了。 </p><p style=\"TEXT-INDENT: 2em\">这是一个天真的男人，一个痛快的男人，一个要强的男人，归根结底是个性情中人。只要你给他配齐人手，他就给你好好干；就像只要你给一个天才纸和笔，他就给你绘出天价名画。如果你什么都不舍得给他，这个淘气包就会赌气似的尿炕，在床单素描出一幅诗意山水图。 </p><p style=\"TEXT-INDENT: 2em\">打爵士的首场白刃战，科比获得创赛季新高的23次罚篮，罚中21枚。这就是他与麦迪的重大差别，麦迪可以在上半场频繁攻击篮筐，而科比可以上下半场持续“强暴”篮筐。麦迪曾说，自己的天赋不输科比。因此，人们喜欢拿麦迪跟科比说事儿。但麦迪存在先天的性格缺陷，他阴柔低调见好就收，科比与之相比更强硬更好胜更不顾性命。 </p><p style=\"TEXT-INDENT: 2em\">爵士悍将布泽尔说，第二场季后赛要在斯坦普斯搞破坏活动，以此吹散科比获奖的喜悦。但，这话千万别让科比听见了。科比从来受不了刺激，他或许会因为你的冒犯而变得更疯狂更嚣张更冷血更无情。 </p><p style=\"TEXT-INDENT: 2em\">千万不要忘记，科比是个为大场面而生的“人来疯”。 </p>');");
E_D("replace into `phome_ecms_news_data_1` values('106','66','QQ','QQ','<table cellspacing=\"0\" cellpadding=\"0\" align=\"center\" border=\"0\" style=\"border-right: #f0bf01 4px solid; border-top: #f0bf01 4px solid; background: url(http://mat1.qq.com/sports/end910/in_tit.gif) #b61503 no-repeat center top; margin: 8px auto; border-left: #f0bf01 4px solid; border-bottom: #f0bf01 4px solid\">\r\n    <tbody>\r\n        <tr>\r\n            <td style=\"padding-right: 10px; padding-left: 10px; padding-bottom: 6px; padding-top: 19px; word-wrap: normal\"><img alt=\"\" src=\"http://img1.qq.com/sports/pics/9015/9015217.jpg\" /></td>\r\n        </tr>\r\n        <tr>\r\n            <td height=\"1\">\r\n            <div class=\"i_left\"><img height=\"7\" alt=\"\" width=\"7\" style=\"left: -4px; top: -2px\" src=\"http://mat1.qq.com/sports/end910/in_3.gif\" /></div>\r\n            <div class=\"i_right\"><img height=\"7\" alt=\"\" width=\"7\" style=\"left: -3px; top: -2px\" src=\"http://mat1.qq.com/sports/end910/in_4.gif\" /></div>\r\n            </td>\r\n        </tr>\r\n    </tbody>\r\n</table>\r\n<!--/link-->\r\n<p align=\"center\"><font size=\"2\">中国男乒第16次捧起斯韦思林杯<br />\r\n</font></p>\r\n<p style=\"text-indent: 2em\">腾讯体育讯　北京时间3月2日晚7点半，第49届世乒赛团体赛展开压轴大戏&mdash;&mdash;男团决赛的争夺。中国队最终凭借马琳、王皓和王励勤三员虎将的出色发挥以3比0干净利落的击败老对手韩国队，延续了世乒赛上逢韩<font face=\"Verdana\">必胜</font>的历史，实现四连冠，历史上第16次捧起斯韦思林杯！</p>\r\n<p style=\"text-indent: 2em\">本届世乒赛中国队此前保持七战全胜，只有王励勤在小组赛对阵罗马尼亚的菲利蒙时丢掉一盘，在淘汰赛阶段中国队以3比0分别击败了捷克队和中国香港队；而韩国队同样保持全胜成绩，在淘汰赛阶段连续淘汰了德国队和日本队。两队在上届不来梅世乒赛上有过交锋纪录，当时中国队以3比0击败对手。</p>');");
E_D("replace into `phome_ecms_news_data_1` values('107','65','网易','网易','<p align=\"center\" style=\"text-indent: 2em\"><strong><img border=\"0\" alt=\"\" src=\"http://cimg20.163.com/2008/2008/5/8/20080508102532f1caa.jpg\" /></strong></p>\r\n<p align=\"center\" style=\"text-indent: 2em\">&nbsp;</p>\r\n<p align=\"center\" style=\"text-indent: 2em\"><strong><img border=\"0\" alt=\"\" src=\"http://cimg20.163.com/2008/2008/5/8/20080508093055a04fc.jpg\" /><br />\r\n</strong>队员在珠峰展示五环旗<br />\r\n&nbsp;</p>\r\n<center><center><center><strong><img border=\"0\" alt=\"\" src=\"http://cimg20.163.com/2008/2008/5/8/200805080921490fe71.jpg\" /><br />\r\n</strong>圣火照亮珠峰<br />\r\n</center><strong><img border=\"0\" alt=\"\" src=\"http://cimg21.163.com/2008/2008/5/8/20080508091958e2cc4.jpg\" /><br />\r\n</strong>火炬手在珠峰峰顶传递<br />\r\n</center><strong><center><img border=\"0\" alt=\"\" src=\"http://cimg20.163.com/2008/2008/5/8/200805080933510c24f.jpg\" /><br />\r\n</center></strong>火炬点燃瞬间</center>\r\n<p style=\"text-indent: 2em\"><strong>珠峰登山队成功登顶 奥运圣火点燃在世界之巅</strong></p>');");
E_D("replace into `phome_ecms_news_data_1` values('108','65','腾讯','腾讯','<p align=\"center\"><img src=\"http://img1.qq.com/sports/pics/10300/10300429.jpg\" border=\"0\" /><br /><strong>科比终于正式接过了本赛季MVP奖杯</strong></p><p style=\"TEXT-INDENT: 2em\">成名这么久远了，科比终于被证实“最有价值”。其实，在世人出于公心的天平上，这位可以与神直接通话的妖人，早已在价值评估体系中占据了统治地位。这次，他仅仅是得到了官方的接纳与认可。全美记者把选票打包一般邮寄给了他，这是通过汗水和血水贿选得来的。据说，在很长一段时间里，科比总喜欢和记者把关系搞僵。现在，科比还是那么牛逼，那么自傲，那么目中无人，那么有折腾劲儿。 </p><p style=\"TEXT-INDENT: 2em\">这是一个对荣誉永远保持饥饿感的男人。他不缺冠军戒指，习惯了腻歪透顶的赢球方式。即便如此，他依然不断向球队索取敲诈胜利。赛季之初，他大骂队友斯玛什·帕克为“极品垃圾”，并要求俱乐部立刻让他从眼前消失。于是，帕克被赶紧打发走了。他是天生的特权球员，飞扬跋扈，大权独揽。他拥有联盟惟一的交易否决选项，拥有挑选队友的生杀权限。他曾经怂恿俱乐部总经理利用拜纳姆来兑换基德，遭否后便大骂总经理“混蛋”。于是，他只得把“自己”作为筹码抛投出去，以离队威胁球队做出改变，迅速强大。如此“雷人”的言论当然会使上峰震怒，就像一位员工总是不断挑拨同事关系扰乱军心，即便是出于好心也会使老板感到不快与拧巴。但，这次闹事的是科比，这是一位大爷，这是一尊大佛，这是一个天真顽劣大声哭闹的大男孩。你惟一可以使局势改观的做法就是哄着他，然后告诉他，叔孰给你买糖吃。 </p><p style=\"TEXT-INDENT: 2em\">随后，湖人总经理出手了。一出手便是大手笔，几乎不废一枪一弹就把加索尔拉来给科比作玩伴儿。这下，男孩儿破涕为笑，不吵不闹，就像是将一颗大白兔兔奶糖含在了小嘴巴里，终于可以蹦蹦跳跳地自个儿玩去了。 </p><p style=\"TEXT-INDENT: 2em\">这是一个天真的男人，一个痛快的男人，一个要强的男人，归根结底是个性情中人。只要你给他配齐人手，他就给你好好干；就像只要你给一个天才纸和笔，他就给你绘出天价名画。如果你什么都不舍得给他，这个淘气包就会赌气似的尿炕，在床单素描出一幅诗意山水图。 </p><p style=\"TEXT-INDENT: 2em\">打爵士的首场白刃战，科比获得创赛季新高的23次罚篮，罚中21枚。这就是他与麦迪的重大差别，麦迪可以在上半场频繁攻击篮筐，而科比可以上下半场持续“强暴”篮筐。麦迪曾说，自己的天赋不输科比。因此，人们喜欢拿麦迪跟科比说事儿。但麦迪存在先天的性格缺陷，他阴柔低调见好就收，科比与之相比更强硬更好胜更不顾性命。 </p><p style=\"TEXT-INDENT: 2em\">爵士悍将布泽尔说，第二场季后赛要在斯坦普斯搞破坏活动，以此吹散科比获奖的喜悦。但，这话千万别让科比听见了。科比从来受不了刺激，他或许会因为你的冒犯而变得更疯狂更嚣张更冷血更无情。 </p><p style=\"TEXT-INDENT: 2em\">千万不要忘记，科比是个为大场面而生的“人来疯”。 </p>');");
E_D("replace into `phome_ecms_news_data_1` values('79','58','','','<p>PHP在业界已经很火了。</p>\r\n<ul>\r\n    <li>Mysql</li>\r\n    <li>Oracle</li>\r\n    <li>Sqllite</li>\r\n    <li>Ingix</li>\r\n</ul>');");
E_D("replace into `phome_ecms_news_data_1` values('80','58','','','<p>It\\\\''s just a demo.</p>\r\n<p>Please contact me!</p>');");
E_D("replace into `phome_ecms_news_data_1` values('81','58','','','<p>测试一下帝国CMS新闻发布！！。。。。。。。。。。。。。。。。</p>');");
E_D("replace into `phome_ecms_news_data_1` values('82','62','','','<p>这是一个测试文章信息,请不要惊慌!!!!!</p>');");
E_D("replace into `phome_ecms_news_data_1` values('86','62','','','<p>的很多很多</p>');");
E_D("replace into `phome_ecms_news_data_1` values('85','62','','','<p>二级审核工作流测试文章啊！！！！</p>');");
E_D("replace into `phome_ecms_news_data_1` values('87','60','','','<p>的很多很多好地方</p>');");
E_D("replace into `phome_ecms_news_data_1` values('88','62','','','<p>撒旦发生大幅</p>');");
E_D("replace into `phome_ecms_news_data_1` values('89','61','','','<p>地方的地方都会地方都会的&nbsp;</p>');");
E_D("replace into `phome_ecms_news_data_1` values('90','61','','','<p>俗的风沙渡&nbsp;</p>');");
E_D("replace into `phome_ecms_news_data_1` values('92','61','','','<p>帝国、CMS、不错、厉害、拮抗剂&nbsp;</p>');");
E_D("replace into `phome_ecms_news_data_1` values('93','61','','','<p>帝国CMS强大、稳定、很好&nbsp;</p>');");
E_D("replace into `phome_ecms_news_data_1` values('109','65','QQ','QQ','<table cellspacing=\"0\" cellpadding=\"0\" align=\"center\" border=\"0\" style=\"border-right: #f0bf01 4px solid; border-top: #f0bf01 4px solid; background: url(http://mat1.qq.com/sports/end910/in_tit.gif) #b61503 no-repeat center top; margin: 8px auto; border-left: #f0bf01 4px solid; border-bottom: #f0bf01 4px solid\">\r\n    <tbody>\r\n        <tr>\r\n            <td style=\"padding-right: 10px; padding-left: 10px; padding-bottom: 6px; padding-top: 19px; word-wrap: normal\"><img alt=\"\" src=\"http://img1.qq.com/sports/pics/9015/9015217.jpg\" /></td>\r\n        </tr>\r\n        <tr>\r\n            <td height=\"1\">\r\n            <div class=\"i_left\"><img height=\"7\" alt=\"\" width=\"7\" style=\"left: -4px; top: -2px\" src=\"http://mat1.qq.com/sports/end910/in_3.gif\" /></div>\r\n            <div class=\"i_right\"><img height=\"7\" alt=\"\" width=\"7\" style=\"left: -3px; top: -2px\" src=\"http://mat1.qq.com/sports/end910/in_4.gif\" /></div>\r\n            </td>\r\n        </tr>\r\n    </tbody>\r\n</table>\r\n<!--/link-->\r\n<p align=\"center\"><font size=\"2\">中国男乒第16次捧起斯韦思林杯<br />\r\n</font></p>\r\n<p style=\"text-indent: 2em\">腾讯体育讯　北京时间3月2日晚7点半，第49届世乒赛团体赛展开压轴大戏&mdash;&mdash;男团决赛的争夺。中国队最终凭借马琳、王皓和王励勤三员虎将的出色发挥以3比0干净利落的击败老对手韩国队，延续了世乒赛上逢韩<font face=\"Verdana\">必胜</font>的历史，实现四连冠，历史上第16次捧起斯韦思林杯！</p>\r\n<p style=\"text-indent: 2em\">本届世乒赛中国队此前保持七战全胜，只有王励勤在小组赛对阵罗马尼亚的菲利蒙时丢掉一盘，在淘汰赛阶段中国队以3比0分别击败了捷克队和中国香港队；而韩国队同样保持全胜成绩，在淘汰赛阶段连续淘汰了德国队和日本队。两队在上届不来梅世乒赛上有过交锋纪录，当时中国队以3比0击败对手。</p>');");

@include("../../inc/footer.php");
?>